### ISSUE TITLE
Add full JSON validation instead of sanity check

### ISSUE THREAD

**Issue by eluzgin** [greymass/producerjson#1]
I think these two lines may become common source of errors if white space included in beginning or end of the JSON string:
    eosio_assert(json[0] == '{',             "payload must be json");
    eosio_assert(json[json.size()-1] == '}', "payload must be json"); 

Since you are not doing true JSON validation - you may as well remove those lines. 
It would be good to include full JSON validation - however that will require adding a new dependency to your contract file:
There are many JSON validation libraries available. We need to check if EOSIO code is already using one and reuse the same one.

**Comment by ScottSallinen** [comment]
White space shouldn't be included in front or behind the payload anyways. Otherwise you have a pretty poorly generated JSON file. Can you give me an example of a JSON generator that includes whitespace in front or behind the {}?

The checks are simple ones to remind the user if the payload is clearly not a JSON file. Doing a full JSON parse of the data would consume a fair amount of CPU on-chain. This is not meant to be a stringent check, only a reminder -- validation of conforming the BP standard JSON should be done client side, as different entities may have relatively strict or loose requirements for validity.

I'll look into a full JSON validation, and see how much CPU that uses.

**Comment by eluzgin** [comment]
Look at fc::json::is_valid(), in fc/includes/fc/io/json.hpp

**Comment by eluzgin** [comment]
In general if you want valid data stored on Blockchain - you can not rely on client validation.

**Comment by ScottSallinen** [comment]
That library is not a contract library, it's part of the `nodeos` and `cleos` code, by the way. A full JSON parser would need to be included in the contract.

Note that the eos forum contract is doing a similar sanity check, and not a full JSON parse as well:
https://github.com/eoscanada/eosio.forum/blob/master/src/forum.cpp#L34

**Comment by eluzgin** [comment]
I agree, closing this issue.
